config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "content#index"

  resources :content do
    post '/down-vote' => 'votes#down_vote', as: :down_vote
    post '/delete-vote' => 'votes#delete_vote', as: :delete_vote
  end

end

app/models/content.rb
class Content < ActiveRecord::Base
  has_many :votes, dependent: :destroy

  def up_votes
    votes.where({value: 1}).count
  end

  def down_votes
    votes.where({value: 1}).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :votes, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :content
  belongs_to :user
  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }

  after_save :update_content

  def up_vote?
    value == 1
  end

  def down_vote?
    value == -1
  end

  private

  def update_content
    content.update_rank
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  def index
    @pieces = Content.paginate(page: params[:page], per_page: 30)
  end

  def show
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  before_action :load_post_and_vote

  def up_vote
    update_vote!(1)
    redirect_to :back
  end

  def down_vote
    update_vote!(-1)
    redirect_to :back
  end

  def delete_vote
    @vote.destroy
    redirect_to :back
  end

  private

  def load_post_and_vote
    @content = Content.find(params[:content_id])

    @vote = @content.votes.where(user_id: current_user.id).first  
  end

  def update_vote!(new_value)
    if @vote
      @vote.update_attribute(:value, new_value)
    else
      @vote = current_user.votes.build(value: new_value, content: @content)
      @vote.save
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/views/content/index.html.erb
<h1>AGRA</h1>
<p>Your daily content:</p>

<div class="pull-right user-info">
  <% if current_user %>
    Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path %> or
    <%= link_to "Sign Up", new_user_registration_path %>
  <% end %>
</div>

<div class="row">
    <% @pieces.each do |content| %>
      <%# render partial: 'votes/voter', locals: {vote: Vote.find_or_initialize_by(content: content, user: current_user) } %>
      <%= render partial: 'votes/voter', locals: { content: content } %>
      <div class="media">
      <h4>
        <%= content.title %>
      </h4>
      <p>
        <%= content.blurb %>
      </p>
      <small>
        <%= content.author %>
      </small>
        <%= content.image %>
    <% end %>
    <%= will_paginate @pieces %>
    </div>
</div>

app/views/content/show.html.erb
<h1>Content#show</h1>
<p>Find me in app/views/content/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agra</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/votes/_voter.html.erb
<div class="pull-left vote-arrows">
  <div><%= link_to " ", content_up_vote_path(content), class: 'glyphicon glyphicon-chevron-up', method: :post %></div>
  <div><strong><%= content.points %></strong></div>
  <div><%= link_to " ", content_down_vote_path(content), class: 'glyphicon glyphicon-chevron-down', method: :post %></div>
</div>